Repository 202303-PRM-TR-FEW/Capstone_Team_8, pull requests merged in 2023-07, with the labels that each got.

#11 Build
  app/firebase.js
  app/firebasetest/page.js
  app/page.js
Labels: documentation

#14 12 authentication
  app/firebase.js
  app/firebasetest/page.js
  app/page.js
Labels: enhancement

#74 Data filtering completed. Scroll to top added.
  app/navigation/page.jsx
  app/projects/page.js
  components/AuthanticatedRoute.jsx
  components/FilterCategories.jsx
  components/PageLayout.jsx
  components/ScrollToTop.jsx
  components/Tabs.jsx
Labels: enhancement

#81 Enchanment
  app/globals.css
  app/myprojects/page.js
  app/project/[id]/page.jsx
  app/search/page.jsx
  app/success/page.js
  app/thankyou/[id]/page.js
  components/MyProjectsCard.jsx
  components/ProgressBar.jsx
  components/TransactionHistory.jsx
  public/5928294_3009287.jpg
Labels: enhancement

#84 Feat
  app/[locale]/globals.css
  app/[locale]/page.js
  app/[locale]/project/[id]/page.jsx
  app/[locale]/projects/page.js
  app/[locale]/thankyou/[id]/page.js
  components/Comment.jsx
  components/Comments.jsx
  components/FilterCategories.jsx
  components/LocaleSwitcher.jsx
  components/Navbar.jsx
  components/ProgressBar.jsx
  components/ProjectCard.jsx
  components/ProjectOfTheWeek.jsx
  components/SearchBar.jsx
  components/SuccesfullProjects.jsx
  components/Tabs.jsx
  messages/en.json
  messages/tr.json
Labels: enhancement

#88 Bug of firebase lang detection fixed
  app/[locale]/layout.js
  app/[locale]/login/page.jsx
  app/[locale]/myprojects/page.js
  app/[locale]/provider.jsx
  app/[locale]/resetpassword/page.jsx
  components/Comments.jsx
  components/EditProject.jsx
  components/LocaleSwitcher.jsx
  components/MyProjectsCard.jsx
  components/Navbar.jsx
  components/ProgressBar.jsx
  components/ProjectCard.jsx
  components/ProjectOfTheWeek.jsx
  components/SuccesfullProjects.jsx
  firebase/firebase.js
  messages/en.json
  messages/tr.json
Labels: bug

#89 Enhance: Multilanguage support
  app/[locale]/login/page.jsx
  app/[locale]/navigation/page.jsx
  app/[locale]/register/page.jsx
  app/[locale]/resetpassword/page.jsx
  app/[locale]/search/page.jsx
  app/[locale]/success/page.js
  components/ConfirmPopUp.jsx
  components/DeleteComment.jsx
  components/EditProject.jsx
  components/FundProject.jsx
  components/KickOffProject.jsx
  components/Login.jsx
  components/Navbar.jsx
  components/Newsletter.jsx
  components/SearchBar.jsx
  components/SuccesfullProjects.jsx
  components/TransactionHistory.jsx
  messages/en.json
  messages/tr.json
Labels: enhancement

#91 bug fixed. translation completed
  app/[locale]/login/page.jsx
  app/[locale]/myprojects/page.js
  app/[locale]/navigation/page.jsx
  app/[locale]/page.js
  app/[locale]/project/[id]/page.jsx
  app/[locale]/projects/page.js
  app/[locale]/register/page.jsx
  app/[locale]/resetpassword/page.jsx
  app/[locale]/thankyou/[id]/page.js
  components/AuthanticatedRoute.jsx
  components/FundProject.jsx
  components/KickOffProject.jsx
  components/Navbar.jsx
  components/ProjectCard.jsx
  components/ProjectOfTheWeek.jsx
  components/SearchBar.jsx
  components/SuccesfullProjects.jsx
  messages/en.json
  messages/tr.json
Labels: bug

#95 Merge branch 'main' into 78-contributors-page
  app/[locale]/contributors/page.js
  public/1668447565144.jpg
  public/1668601656647.jpg
  public/1685543987007.jpg
  public/B598FE0E-8020-4276-9FD1-8F0E06CF1A44.jpg
  public/channels4_profile.jpg
Labels: enhancement

#99 97 follow users
  app/[locale]/myprojects/page.js
  app/[locale]/project/[id]/page.jsx
  app/[locale]/users/[id]/page.js
  components/ChangePassword.jsx
  components/Comments.jsx
  components/Follow.jsx
  components/ProfileInfo.jsx
  components/ProjectOfTheWeek.jsx
  components/SuccesfullProjects.jsx
  components/TopDonors.jsx
  components/TransactionHistory.jsx
  firebase/firebase.js
  messages/en.json
  messages/tr.json
Labels: enhancement

#101 Enchance user page design
  app/[locale]/users/[id]/page.js
  components/Comments.jsx
  components/Follow.jsx
  components/Followers.jsx
  components/ProfileInfo.jsx
  components/ProfilePageTab.jsx
  components/TopDonors.jsx
  firebase/firebase.js
  messages/en.json
  messages/tr.json
Labels: enhancement

#102 Feat
  app/[locale]/about/page.js
  messages/en.json
  messages/tr.json
Labels: enhancement

#104 enhancement
  app/[locale]/users/[id]/page.js
  components/Followers.jsx
Labels: enhancement

#106 94 contributors page
  app/[locale]/contributors/page.js
Labels: enhancement

#107 Feat Multilanguage
  app/[locale]/contributors/page.js
  messages/en.json
  messages/tr.json
Labels: enhancement

#113 Enhance UI
  app/[locale]/contributors/page.js
  app/[locale]/users/[id]/page.js
  components/Footer.jsx
  components/ProfilePageTab.jsx
  components/UserDonatedProjects.jsx
  components/UserProfileTabs.jsx
  components/UsersProjects.jsx
  messages/en.json
  messages/tr.json
Labels: enhancement
